# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-25 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry_Title',
            new_name='EntryTitle',
        ),
    ]
