# Generated by Django 3.1.7 on 2021-03-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20210303_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='public',
        ),
        migrations.AddField(
            model_name='entrytitle',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
